### ISSUE TITLE
Exception caught rockhounding_core version 1.12.2-3.28

### ISSUE THREAD

**Issue by xkforce** [GlobbyPotato/Rockhounding_Rocks#19]
---- Minecraft Crash Report ----
// Oops.

Time: 5/15/23 8:15 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Rockhounding: Rocks (rockhounding_rocks)
Caused by: java.lang.NoClassDefFoundError: com/globbypotato/rockhounding_rocks/utils/IMCUtils
	at com.globbypotato.rockhounding_rocks.proxy.CommonProxy.imcInit(CommonProxy.java:53)
	at com.globbypotato.rockhounding_rocks.proxy.ClientProxy.imcInit(ClientProxy.java:30)
	at com.globbypotato.rockhounding_rocks.Rhrocks.handleIMCMessage(Rhrocks.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:320)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:752)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.globbypotato.rockhounding_rocks.utils.IMCUtils
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 44 more
Caused by: java.lang.NoClassDefFoundError: rockhounding/api/IReciperBase
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 46 more
Caused by: java.lang.ClassNotFoundException: rockhounding.api.IReciperBase
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 50 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.15.0-71-generic
	Java Version: 1.8.0_312, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 217366960 bytes (207 MB) / 1225261056 bytes (1168 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -Xmx4096m -Xms4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 7 mods loaded, 7 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                 | Version      | Source                             | Signature                                |
	|:----- |:------------------ |:------------ |:---------------------------------- |:---------------------------------------- |
	| LCHI  | minecraft          | 1.12.2       | minecraft.jar                      | None                                     |
	| LCHI  | mcp                | 9.42         | minecraft.jar                      | None                                     |
	| LCHI  | FML                | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | forge              | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHI  | gbook              | 2.9.5        | Guidebook-1.12.2-2.9.5.jar         | None                                     |
	| LCHI  | rockhounding_core  | 3.28         | rockhounding_core-1.12.2-3.28.jar  | None                                     |
	| LCHIE | rockhounding_rocks | 1.12.2-3.21  | rockhounding_rocks-1.12.2-3.21.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 525.105.17' Renderer: 'NVIDIA GeForce RTX 2070/PCIe/SSE2'

**Comment by GlobbyPotato** [comment]
Hi, try reducing the core version to 3.27 to see if it solves
